import { Injectable } from "@angular/core";
import { InMemoryDbService } from "angular-in-memory-web-api";
import { Player } from "../models/player";

@Injectable({
  providedIn: "root",
})
export class InMemoryDataService implements InMemoryDbService {
  createDb() {
    const players = [
      {
        id: 1,
        name: "Nathan Armour",
        jersey_number: 1,
        year: "Junior",
        position: "Cutter",
        fav_food: "Ice Cream",
        team_id: 1,
      },
      {
        id: 2,
        name: "Luiz Astorga",
        jersey_number: 1,
        year: "Junior",
        position: "Cutter",
        fav_food: "Ice Cream",
        team_id: 1,
      },
      {
        id: 3,
        name: "Emmanual Bilolo",
        jersey_number: 1,
        year: "Junior",
        position: "Cutter",
        fav_food: "Ice Cream",
        team_id: 1,
      },
      {
        id: 4,
        name: "Eric Chen",
        jersey_number: 1,
        year: "Junior",
        position: "Cutter",
        fav_food: "Ice Cream",
        team_id: 1,
      },
      {
        id: 5,
        name: "Christian Cortes",
        jersey_number: 1,
        year: "Junior",
        position: "Cutter",
        fav_food: "Ice Cream",
        team_id: 1,
      },
      {
        id: 6,
        name: "Jason Dick",
        jersey_number: 1,
        year: "Junior",
        position: "Cutter",
        fav_food: "Ice Cream",
        team_id: 1,
      },
      {
        id: 7,
        name: "Cristopher Fogel",
        jersey_number: 1,
        year: "Junior",
        position: "Cutter",
        fav_food: "Ice Cream",
        team_id: 1,
      },
      {
        id: 8,
        name: "Steven Gomez",
        jersey_number: 1,
        year: "Junior",
        position: "Cutter",
        fav_food: "Ice Cream",
        team_id: 1,
      },
      {
        id: 9,
        name: "Colton Green",
        jersey_number: 1,
        year: "Junior",
        position: "Cutter",
        fav_food: "Ice Cream",
        team_id: 1,
      },
      {
        id: 10,
        name: "Alvaro (Noe) Guzman",
        jersey_number: 1,
        year: "Junior",
        position: "Cutter",
        fav_food: "Ice Cream",
        team_id: 1,
      },
      {
        id: 11,
        name: "Logan Harless",
        jersey_number: 1,
        year: "Junior",
        position: "Cutter",
        fav_food: "Ice Cream",
        team_id: 1,
      },
      {
        id: 12,
        name: "Alexander Ho",
        jersey_number: 1,
        year: "Junior",
        position: "Cutter",
        fav_food: "Ice Cream",
        team_id: 1,
      },
      {
        id: 13,
        name: "Tristan Ho",
        jersey_number: 1,
        year: "Junior",
        position: "Cutter",
        fav_food: "Ice Cream",
        team_id: 1,
      },
      {
        id: 14,
        name: "Brian Honea",
        jersey_number: 1,
        year: "Junior",
        position: "Cutter",
        fav_food: "Ice Cream",
        team_id: 1,
      },
      {
        id: 15,
        name: "Julius Hubby",
        jersey_number: 1,
        year: "Junior",
        position: "Cutter",
        fav_food: "Ice Cream",
        team_id: 1,
      },
      {
        id: 16,
        name: "Jason Hustad",
        jersey_number: 1,
        year: "Junior",
        position: "Cutter",
        fav_food: "Ice Cream",
        team_id: 1,
      },
      {
        id: 17,
        name: "Tyler Hustad",
        jersey_number: 1,
        year: "Junior",
        position: "Cutter",
        fav_food: "Ice Cream",
        team_id: 1,
      },
      {
        id: 18,
        name: "Eric Kleckner",
        jersey_number: 1,
        year: "Junior",
        position: "Cutter",
        fav_food: "Ice Cream",
        team_id: 1,
      },
      {
        id: 19,
        name: "Victor Mao",
        jersey_number: 1,
        year: "Junior",
        position: "Cutter",
        fav_food: "Ice Cream",
        team_id: 1,
      },
      {
        id: 20,
        name: "Wesley Miaw",
        jersey_number: 1,
        year: "Junior",
        position: "Cutter",
        fav_food: "Ice Cream",
        team_id: 1,
      },
      {
        id: 21,
        name: "Nand Patel",
        jersey_number: 1,
        year: "Junior",
        position: "Cutter",
        fav_food: "Ice Cream",
        team_id: 1,
      },
      {
        id: 22,
        name: "Benny Rubanov",
        jersey_number: 1,
        year: "Junior",
        position: "Cutter",
        fav_food: "Ice Cream",
        team_id: 1,
      },
      {
        id: 23,
        name: "Daniel Urrutia",
        jersey_number: 1,
        year: "Junior",
        position: "Cutter",
        fav_food: "Ice Cream",
        team_id: 1,
      },
      {
        id: 23,
        name: "Daniel Urrutia",
        jersey_number: 1,
        year: "Junior",
        position: "Cutter",
        fav_food: "Ice Cream",
        team_id: 1,
      },
      {
        id: 23,
        name: "Jonathan Brandt",
        jersey_number: 1,
        year: "Junior",
        position: "Cutter",
        fav_food: "Ice Cream",
        team_id: 2,
      },
      {
        id: 24,
        name: "Neel Moni",
        jersey_number: 1,
        year: "Junior",
        position: "Cutter",
        fav_food: "Ice Cream",
        team_id: 2,
      },
      {
        id: 25,
        name: "Timothy Champion",
        jersey_number: 1,
        year: "Junior",
        position: "Cutter",
        fav_food: "Ice Cream",
        team_id: 2,
      },
      {
        id: 26,
        name: "Nik Vadodaria",
        jersey_number: 1,
        year: "Junior",
        position: "Cutter",
        fav_food: "Ice Cream",
        team_id: 2,
      },
      {
        id: 27,
        name: "John Novosel",
        jersey_number: 1,
        year: "Junior",
        position: "Cutter",
        fav_food: "Ice Cream",
        team_id: 2,
      },
      {
        id: 28,
        name: "Naved Yekanizaree",
        jersey_number: 1,
        year: "Junior",
        position: "Cutter",
        fav_food: "Ice Cream",
        team_id: 2,
      },
      {
        id: 29,
        name: "Craig Hilby",
        jersey_number: 1,
        year: "Junior",
        position: "Cutter",
        fav_food: "Ice Cream",
        team_id: 2,
      },
      {
        id: 30,
        name: "Michael Chen",
        jersey_number: 1,
        year: "Junior",
        position: "Cutter",
        fav_food: "Ice Cream",
        team_id: 2,
      },
      {
        id: 31,
        name: "Kumar Kudumula",
        jersey_number: 1,
        year: "Junior",
        position: "Cutter",
        fav_food: "Ice Cream",
        team_id: 2,
      },
      {
        id: 32,
        name: "Victor Lopez",
        jersey_number: 1,
        year: "Junior",
        position: "Cutter",
        fav_food: "Ice Cream",
        team_id: 2,
      },
      {
        id: 33,
        name: "Ciro Randazzo",
        jersey_number: 1,
        year: "Junior",
        position: "Cutter",
        fav_food: "Ice Cream",
        team_id: 2,
      },
      {
        id: 34,
        name: "Dylan Nguyen",
        jersey_number: 1,
        year: "Junior",
        position: "Cutter",
        fav_food: "Ice Cream",
        team_id: 2,
      },
      {
        id: 35,
        name: "Chaithu Dikkala",
        jersey_number: 1,
        year: "Junior",
        position: "Cutter",
        fav_food: "Ice Cream",
        team_id: 2,
      },
      {
        id: 36,
        name: "Anh Nguyen",
        jersey_number: 1,
        year: "Junior",
        position: "Cutter",
        fav_food: "Ice Cream",
        team_id: 2,
      },
      {
        id: 37,
        name: "Sanjay Srikanth",
        jersey_number: 1,
        year: "Junior",
        position: "Cutter",
        fav_food: "Ice Cream",
        team_id: 2,
      },
      {
        id: 38,
        name: "Michael McCall",
        jersey_number: 1,
        year: "Junior",
        position: "Cutter",
        fav_food: "Ice Cream",
        team_id: 2,
      },
      {
        id: 39,
        name: "Kyle Tupper",
        jersey_number: 1,
        year: "Junior",
        position: "Cutter",
        fav_food: "Ice Cream",
        team_id: 2,
      },
      {
        id: 40,
        name: "William Benson",
        jersey_number: 1,
        year: "Junior",
        position: "Cutter",
        fav_food: "Ice Cream",
        team_id: 2,
      },
      {
        id: 41,
        name: "Michael Goldenstein",
        jersey_number: 1,
        year: "Junior",
        position: "Cutter",
        fav_food: "Ice Cream",
        team_id: 2,
      },
      {
        id: 42,
        name: "Brandon Sike",
        jersey_number: 1,
        year: "Junior",
        position: "Cutter",
        fav_food: "Ice Cream",
        team_id: 2,
      },
      {
        id: 43,
        name: "Brendan Paul",
        jersey_number: 1,
        year: "Junior",
        position: "Cutter",
        fav_food: "Ice Cream",
        team_id: 2,
      },
      {
        id: 44,
        name: "Tandav Argula",
        jersey_number: 1,
        year: "Junior",
        position: "Cutter",
        fav_food: "Ice Cream",
        team_id: 2,
      },
      {
        id: 45,
        name: "Ben Morrison",
        jersey_number: 1,
        year: "Junior",
        position: "Cutter",
        fav_food: "Ice Cream",
        team_id: 2,
      },
      {
        id: 46,
        name: "Kaustub Nair",
        jersey_number: 1,
        year: "Junior",
        position: "Cutter",
        fav_food: "Ice Cream",
        team_id: 2,
      },
      {
        id: 47,
        name: "David Piersall",
        jersey_number: 1,
        year: "Junior",
        position: "Cutter",
        fav_food: "Ice Cream",
        team_id: 2,
      },
      {
        id: 48,
        name: "William Payne",
        jersey_number: 1,
        year: "Junior",
        position: "Cutter",
        fav_food: "Ice Cream",
        team_id: 2,
      },
      {
        id: 49,
        name: "Caleb Trotter",
        jersey_number: 1,
        year: "Junior",
        position: "Cutter",
        fav_food: "Ice Cream",
        team_id: 2,
      },
      {
        id: 50,
        name: "Elissa Balke",
        jersey_number: 1,
        year: "Junior",
        position: "Cutter",
        fav_food: "Ice Cream",
        team_id: 3,
      },
      {
        id: 51,
        name: "Anne Chan",
        jersey_number: 1,
        year: "Junior",
        position: "Cutter",
        fav_food: "Ice Cream",
        team_id: 3,
      },
      {
        id: 52,
        name: "Allison Chang",
        jersey_number: 1,
        year: "Junior",
        position: "Cutter",
        fav_food: "Ice Cream",
        team_id: 3,
      },
      {
        id: 53,
        name: "Rebecca Chase",
        jersey_number: 1,
        year: "Junior",
        position: "Cutter",
        fav_food: "Ice Cream",
        team_id: 3,
      },
      {
        id: 54,
        name: "Ashley Gi",
        jersey_number: 1,
        year: "Junior",
        position: "Cutter",
        fav_food: "Ice Cream",
        team_id: 3,
      },
      {
        id: 55,
        name: "Jennifer Good",
        jersey_number: 1,
        year: "Junior",
        position: "Cutter",
        fav_food: "Ice Cream",
        team_id: 3,
      },
      {
        id: 56,
        name: "Elizabeth Higgins",
        jersey_number: 1,
        year: "Junior",
        position: "Cutter",
        fav_food: "Ice Cream",
        team_id: 3,
      },
      {
        id: 57,
        name: "Negin Khakpour",
        jersey_number: 1,
        year: "Junior",
        position: "Cutter",
        fav_food: "Ice Cream",
        player_photo: "../../assets/player-photos/Negin Khakpour.jpg",
        team_id: 3,
      },
      {
        id: 58,
        name: "Julia Mihail",
        jersey_number: 1,
        year: "Junior",
        position: "Cutter",
        fav_food: "Ice Cream",
        team_id: 3,
      },
      {
        id: 59,
        name: "Jennifer Nguyen",
        jersey_number: 1,
        year: "Junior",
        position: "Cutter",
        fav_food: "Ice Cream",
        team_id: 3,
      },
      {
        id: 60,
        name: "Dom O'Neill",
        jersey_number: 1,
        year: "Junior",
        position: "Cutter",
        fav_food: "Ice Cream",
        team_id: 3,
      },
      {
        id: 61,
        name: "Sofia Sacco",
        jersey_number: 1,
        year: "Junior",
        position: "Cutter",
        fav_food: "Ice Cream",
        team_id: 3,
      },
      {
        id: 62,
        name: "Nupur Sampat",
        jersey_number: 1,
        year: "Junior",
        position: "Cutter",
        fav_food: "Ice Cream",
        team_id: 3,
      },
      {
        id: 63,
        name: "Shruthi Subramanium",
        jersey_number: 1,
        year: "Junior",
        position: "Cutter",
        fav_food: "Ice Cream",
        team_id: 3,
      },
      {
        id: 64,
        name: "Brianne McLemore",
        jersey_number: 1,
        year: "Junior",
        position: "Cutter",
        fav_food: "Ice Cream",
        player_photo: "../../assets/player-photos/Brianne McLemore.jpg",
        team_id: 3,
      },
      {
        id: 65,
        name: "LeAnn Le",
        jersey_number: 1,
        year: "Junior",
        position: "Cutter",
        fav_food: "Ice Cream",
        team_id: 3,
      },
      {
        id: 66,
        name: "Corrina Spurlin",
        jersey_number: 1,
        year: "Junior",
        position: "Cutter",
        fav_food: "Ice Cream",
        team_id: 3,
      },
      {
        id: 67,
        name: "Madison Nickerson",
        jersey_number: 1,
        year: "Junior",
        position: "Cutter",
        fav_food: "Ice Cream",
        team_id: 3,
      },
      {
        id: 68,
        name: "Camille Gerstner",
        jersey_number: 1,
        year: "Junior",
        position: "Cutter",
        fav_food: "Ice Cream",
        player_photo: "../../assets/player-photos/Camille Gerstner.jpg",
        team_id: 3,
      },
      {
        id: 69,
        name: "Jamie Eriksson",
        jersey_number: 1,
        year: "Junior",
        position: "Cutter",
        fav_food: "Ice Cream",
        team_id: 3,
      },
      {
        id: 70,
        name: "Kylee Glenn",
        jersey_number: 1,
        year: "Junior",
        position: "Cutter",
        fav_food: "Ice Cream",
        team_id: 3,
      },
      {
        id: 71,
        name: "Celeste Bilolo",
        jersey_number: 1,
        year: "Junior",
        position: "Cutter",
        fav_food: "Ice Cream",
        team_id: 3,
      },
      {
        id: 72,
        name: "Emma Bronnenberg",
        jersey_number: 1,
        year: "Junior",
        position: "Cutter",
        fav_food: "Ice Cream",
        player_photo: "../../assets/player-photos/Emma Bronnenberg.jpg",
        team_id: 3,
      },
      {
        id: 73,
        name: "Olivia Osborne",
        jersey_number: 1,
        year: "Junior",
        position: "Cutter",
        fav_food: "Ice Cream",
        player_photo: "../../assets/player-photos/Olivia Osborne.jpg",
        team_id: 3,
      },
      {
        id: 74,
        name: "Jacqueline Pham",
        jersey_number: 1,
        year: "Junior",
        position: "Cutter",
        fav_food: "Ice Cream",
        team_id: 3,
      },
      {
        id: 75,
        name: "Olivia Bonin",
        jersey_number: 1,
        year: "Junior",
        position: "Cutter",
        fav_food: "Ice Cream",
        team_id: 3,
      },
      {
        id: 76,
        name: "Bristol Lovoy",
        jersey_number: 1,
        year: "Junior",
        position: "Cutter",
        fav_food: "Ice Cream",
        team_id: 3,
      },
    ];
    const teams = [
      {
        id: 1,
        name: "WOOF-A",
        roster: [
          {
            id: 1,
            name: "Nathan Armour",
            jersey_number: 1,
            year: "Junior",
            position: "Cutter",
            fav_food: "Ice Cream",

            team_id: 1,
          },
          {
            id: 2,
            name: "Luiz Astorga",
            jersey_number: 1,
            year: "Junior",
            position: "Cutter",
            fav_food: "Ice Cream",

            team_id: 1,
          },
          {
            id: 3,
            name: "Emmanual Bilolo",
            jersey_number: 1,
            year: "Junior",
            position: "Cutter",
            fav_food: "Ice Cream",

            team_id: 1,
          },
          {
            id: 4,
            name: "Eric Chen",
            jersey_number: 1,
            year: "Junior",
            position: "Cutter",
            fav_food: "Ice Cream",

            team_id: 1,
          },
          {
            id: 5,
            name: "Christian Cortes",
            jersey_number: 1,
            year: "Junior",
            position: "Cutter",
            fav_food: "Ice Cream",

            team_id: 1,
          },
          {
            id: 6,
            name: "Jason Dick",
            jersey_number: 1,
            year: "Junior",
            position: "Cutter",
            fav_food: "Ice Cream",

            team_id: 1,
          },
          {
            id: 7,
            name: "Cristopher Fogel",
            jersey_number: 1,
            year: "Junior",
            position: "Cutter",
            fav_food: "Ice Cream",

            team_id: 1,
          },
          {
            id: 8,
            name: "Steven Gomez",
            jersey_number: 1,
            year: "Junior",
            position: "Cutter",
            fav_food: "Ice Cream",

            team_id: 1,
          },
          {
            id: 9,
            name: "Colton Green",
            jersey_number: 1,
            year: "Junior",
            position: "Cutter",
            fav_food: "Ice Cream",

            team_id: 1,
          },
          {
            id: 10,
            name: "Alvaro (Noe) Guzman",
            jersey_number: 1,
            year: "Junior",
            position: "Cutter",
            fav_food: "Ice Cream",

            team_id: 1,
          },
          {
            id: 11,
            name: "Logan Harless",
            jersey_number: 1,
            year: "Junior",
            position: "Cutter",
            fav_food: "Ice Cream",

            team_id: 1,
          },
          {
            id: 12,
            name: "Alexander Ho",
            jersey_number: 1,
            year: "Junior",
            position: "Cutter",
            fav_food: "Ice Cream",

            team_id: 1,
          },
          {
            id: 13,
            name: "Tristan Ho",
            jersey_number: 1,
            year: "Junior",
            position: "Cutter",
            fav_food: "Ice Cream",

            team_id: 1,
          },
          {
            id: 14,
            name: "Brian Honea",
            jersey_number: 1,
            year: "Junior",
            position: "Cutter",
            fav_food: "Ice Cream",

            team_id: 1,
          },
          {
            id: 15,
            name: "Julius Hubby",
            jersey_number: 1,
            year: "Junior",
            position: "Cutter",
            fav_food: "Ice Cream",

            team_id: 1,
          },
          {
            id: 16,
            name: "Jason Hustad",
            jersey_number: 1,
            year: "Junior",
            position: "Cutter",
            fav_food: "Ice Cream",

            team_id: 1,
          },
          {
            id: 17,
            name: "Tyler Hustad",
            jersey_number: 1,
            year: "Junior",
            position: "Cutter",
            fav_food: "Ice Cream",

            team_id: 1,
          },
          {
            id: 18,
            name: "Eric Kleckner",
            jersey_number: 1,
            year: "Junior",
            position: "Cutter",
            fav_food: "Ice Cream",

            team_id: 1,
          },
          {
            id: 19,
            name: "Victor Mao",
            jersey_number: 1,
            year: "Junior",
            position: "Cutter",
            fav_food: "Ice Cream",

            team_id: 1,
          },
          {
            id: 20,
            name: "Wesley Miaw",
            jersey_number: 1,
            year: "Junior",
            position: "Cutter",
            fav_food: "Ice Cream",

            team_id: 1,
          },
          {
            id: 21,
            name: "Nand Patel",
            jersey_number: 1,
            year: "Junior",
            position: "Cutter",
            fav_food: "Ice Cream",

            team_id: 1,
          },
          {
            id: 22,
            name: "Benny Rubanov",
            jersey_number: 1,
            year: "Junior",
            position: "Cutter",
            fav_food: "Ice Cream",

            team_id: 1,
          },
          {
            id: 23,
            name: "Daniel Urrutia",
            jersey_number: 1,
            year: "Junior",
            position: "Cutter",
            fav_food: "Ice Cream",

            team_id: 1,
          },
          {
            id: 23,
            name: "Daniel Urrutia",
            jersey_number: 1,
            year: "Junior",
            position: "Cutter",
            fav_food: "Ice Cream",

            team_id: 1,
          },
        ],
      },
      {
        id: 2,
        name: "WOOF-B",
        roster: [
          {
            id: 23,
            name: "Jonathan Brandt",
            jersey_number: 1,
            year: "Junior",
            position: "Cutter",
            fav_food: "Ice Cream",
            team_id: 2,
          },
          {
            id: 24,
            name: "Neel Moni",
            jersey_number: 1,
            year: "Junior",
            position: "Cutter",
            fav_food: "Ice Cream",
            team_id: 2,
          },
          {
            id: 25,
            name: "Timothy Champion",
            jersey_number: 1,
            year: "Junior",
            position: "Cutter",
            fav_food: "Ice Cream",
            team_id: 2,
          },
          {
            id: 26,
            name: "Nik Vadodaria",
            jersey_number: 1,
            year: "Junior",
            position: "Cutter",
            fav_food: "Ice Cream",
            team_id: 2,
          },
          {
            id: 27,
            name: "John Novosel",
            jersey_number: 1,
            year: "Junior",
            position: "Cutter",
            fav_food: "Ice Cream",
            team_id: 2,
          },
          {
            id: 28,
            name: "Naved Yekanizaree",
            jersey_number: 1,
            year: "Junior",
            position: "Cutter",
            fav_food: "Ice Cream",
            team_id: 2,
          },
          {
            id: 29,
            name: "Craig Hilby",
            jersey_number: 1,
            year: "Junior",
            position: "Cutter",
            fav_food: "Ice Cream",
            team_id: 2,
          },
          {
            id: 30,
            name: "Michael Chen",
            jersey_number: 1,
            year: "Junior",
            position: "Cutter",
            fav_food: "Ice Cream",
            team_id: 2,
          },
          {
            id: 31,
            name: "Kumar Kudumula",
            jersey_number: 1,
            year: "Junior",
            position: "Cutter",
            fav_food: "Ice Cream",
            team_id: 2,
          },
          {
            id: 32,
            name: "Victor Lopez",
            jersey_number: 1,
            year: "Junior",
            position: "Cutter",
            fav_food: "Ice Cream",
            team_id: 2,
          },
          {
            id: 33,
            name: "Ciro Randazzo",
            jersey_number: 1,
            year: "Junior",
            position: "Cutter",
            fav_food: "Ice Cream",
            team_id: 2,
          },
          {
            id: 34,
            name: "Dylan Nguyen",
            jersey_number: 1,
            year: "Junior",
            position: "Cutter",
            fav_food: "Ice Cream",
            team_id: 2,
          },
          {
            id: 35,
            name: "Chaithu Dikkala",
            jersey_number: 1,
            year: "Junior",
            position: "Cutter",
            fav_food: "Ice Cream",
            team_id: 2,
          },
          {
            id: 36,
            name: "Anh Nguyen",
            jersey_number: 1,
            year: "Junior",
            position: "Cutter",
            fav_food: "Ice Cream",
            team_id: 2,
          },
          {
            id: 37,
            name: "Sanjay Srikanth",
            jersey_number: 1,
            year: "Junior",
            position: "Cutter",
            fav_food: "Ice Cream",
            team_id: 2,
          },
          {
            id: 38,
            name: "Michael McCall",
            jersey_number: 1,
            year: "Junior",
            position: "Cutter",
            fav_food: "Ice Cream",
            team_id: 2,
          },
          {
            id: 39,
            name: "Kyle Tupper",
            jersey_number: 1,
            year: "Junior",
            position: "Cutter",
            fav_food: "Ice Cream",
            team_id: 2,
          },
          {
            id: 40,
            name: "William Benson",
            jersey_number: 1,
            year: "Junior",
            position: "Cutter",
            fav_food: "Ice Cream",
            team_id: 2,
          },
          {
            id: 41,
            name: "Michael Goldenstein",
            jersey_number: 1,
            year: "Junior",
            position: "Cutter",
            fav_food: "Ice Cream",
            team_id: 2,
          },
          {
            id: 42,
            name: "Brandon Sike",
            jersey_number: 1,
            year: "Junior",
            position: "Cutter",
            fav_food: "Ice Cream",
            team_id: 2,
          },
          {
            id: 43,
            name: "Brendan Paul",
            jersey_number: 1,
            year: "Junior",
            position: "Cutter",
            fav_food: "Ice Cream",
            team_id: 2,
          },
          {
            id: 44,
            name: "Tandav Argula",
            jersey_number: 1,
            year: "Junior",
            position: "Cutter",
            fav_food: "Ice Cream",
            team_id: 2,
          },
          {
            id: 45,
            name: "Ben Morrison",
            jersey_number: 1,
            year: "Junior",
            position: "Cutter",
            fav_food: "Ice Cream",
            team_id: 2,
          },
          {
            id: 46,
            name: "Kaustub Nair",
            jersey_number: 1,
            year: "Junior",
            position: "Cutter",
            fav_food: "Ice Cream",
            team_id: 2,
          },
          {
            id: 47,
            name: "David Piersall",
            jersey_number: 1,
            year: "Junior",
            position: "Cutter",
            fav_food: "Ice Cream",
            team_id: 2,
          },
          {
            id: 48,
            name: "William Payne",
            jersey_number: 1,
            year: "Junior",
            position: "Cutter",
            fav_food: "Ice Cream",
            team_id: 2,
          },
          {
            id: 49,
            name: "Caleb Trotter",
            jersey_number: 1,
            year: "Junior",
            position: "Cutter",
            fav_food: "Ice Cream",
            team_id: 2,
          },
        ],
      },
      {
        id: 3,
        name: "Whiplash",
        roster: [
          {
            id: 50,
            name: "Elissa Balke",
            jersey_number: 1,
            year: "Junior",
            position: "Cutter",
            fav_food: "Ice Cream",
            team_id: 3,
          },
          {
            id: 51,
            name: "Anne Chan",
            jersey_number: 1,
            year: "Junior",
            position: "Cutter",
            fav_food: "Ice Cream",
            team_id: 3,
          },
          {
            id: 52,
            name: "Allison Chang",
            jersey_number: 1,
            year: "Junior",
            position: "Cutter",
            fav_food: "Ice Cream",
            team_id: 3,
          },
          {
            id: 53,
            name: "Rebecca Chase",
            jersey_number: 1,
            year: "Junior",
            position: "Cutter",
            fav_food: "Ice Cream",
            team_id: 3,
          },
          {
            id: 54,
            name: "Ashley Gi",
            jersey_number: 1,
            year: "Junior",
            position: "Cutter",
            fav_food: "Ice Cream",
            team_id: 3,
          },
          {
            id: 55,
            name: "Jennifer Good",
            jersey_number: 1,
            year: "Junior",
            position: "Cutter",
            fav_food: "Ice Cream",
            team_id: 3,
          },
          {
            id: 56,
            name: "Elizabeth Higgins",
            jersey_number: 1,
            year: "Junior",
            position: "Cutter",
            fav_food: "Ice Cream",
            team_id: 3,
          },
          {
            id: 57,
            name: "Negin Khakpour",
            jersey_number: 1,
            year: "Junior",
            position: "Cutter",
            fav_food: "Ice Cream",
            player_photo: "../../assets/player-photos/Negin Khakpour.jpg",
            team_id: 3,
          },
          {
            id: 58,
            name: "Julia Mihail",
            jersey_number: 1,
            year: "Junior",
            position: "Cutter",
            fav_food: "Ice Cream",
            team_id: 3,
          },
          {
            id: 59,
            name: "Jennifer Nguyen",
            jersey_number: 1,
            year: "Junior",
            position: "Cutter",
            fav_food: "Ice Cream",
            team_id: 3,
          },
          {
            id: 60,
            name: "Dom O'Neill",
            jersey_number: 1,
            year: "Junior",
            position: "Cutter",
            fav_food: "Ice Cream",
            team_id: 3,
          },
          {
            id: 61,
            name: "Sofia Sacco",
            jersey_number: 1,
            year: "Junior",
            position: "Cutter",
            fav_food: "Ice Cream",
            team_id: 3,
          },
          {
            id: 62,
            name: "Nupur Sampat",
            jersey_number: 1,
            year: "Junior",
            position: "Cutter",
            fav_food: "Ice Cream",
            team_id: 3,
          },
          {
            id: 63,
            name: "Shruthi Subramanium",
            jersey_number: 1,
            year: "Junior",
            position: "Cutter",
            fav_food: "Ice Cream",
            team_id: 3,
          },
          {
            id: 64,
            name: "Brianne McLemore",
            jersey_number: 1,
            year: "Junior",
            position: "Cutter",
            fav_food: "Ice Cream",
            player_photo: "../../assets/player-photos/Brianne McLemore.jpg",
            team_id: 3,
          },
          {
            id: 65,
            name: "LeAnn Le",
            jersey_number: 1,
            year: "Junior",
            position: "Cutter",
            fav_food: "Ice Cream",
            team_id: 3,
          },
          {
            id: 66,
            name: "Corrina Spurlin",
            jersey_number: 1,
            year: "Junior",
            position: "Cutter",
            fav_food: "Ice Cream",
            team_id: 3,
          },
          {
            id: 67,
            name: "Madison Nickerson",
            jersey_number: 1,
            year: "Junior",
            position: "Cutter",
            fav_food: "Ice Cream",
            team_id: 3,
          },
          {
            id: 68,
            name: "Camille Gerstner",
            jersey_number: 1,
            year: "Junior",
            position: "Cutter",
            fav_food: "Ice Cream",
            player_photo: "../../assets/player-photos/Camille Gerstner.jpg",
            team_id: 3,
          },
          {
            id: 69,
            name: "Jamie Eriksson",
            jersey_number: 1,
            year: "Junior",
            position: "Cutter",
            fav_food: "Ice Cream",
            team_id: 3,
          },
          {
            id: 70,
            name: "Kylee Glenn",
            jersey_number: 1,
            year: "Junior",
            position: "Cutter",
            fav_food: "Ice Cream",
            team_id: 3,
          },
          {
            id: 71,
            name: "Celeste Bilolo",
            jersey_number: 1,
            year: "Junior",
            position: "Cutter",
            fav_food: "Ice Cream",
            team_id: 3,
          },
          {
            id: 72,
            name: "Emma Bronnenberg",
            jersey_number: 1,
            year: "Junior",
            position: "Cutter",
            fav_food: "Ice Cream",
            player_photo: "../../assets/player-photos/Emma Bronnenberg.jpg",
            team_id: 3,
          },
          {
            id: 73,
            name: "Olivia Osborne",
            jersey_number: 1,
            year: "Junior",
            position: "Cutter",
            fav_food: "Ice Cream",
            player_photo: "../../assets/player-photos/Olivia Osborne.jpg",
            team_id: 3,
          },
          {
            id: 74,
            name: "Jacqueline Pham",
            jersey_number: 1,
            year: "Junior",
            position: "Cutter",
            fav_food: "Ice Cream",
            team_id: 3,
          },
          {
            id: 75,
            name: "Olivia Bonin",
            jersey_number: 1,
            year: "Junior",
            position: "Cutter",
            fav_food: "Ice Cream",
            team_id: 3,
          },
          {
            id: 76,
            name: "Bristol Lovoy",
            jersey_number: 1,
            year: "Junior",
            position: "Cutter",
            fav_food: "Ice Cream",
            team_id: 3,
          },
        ],
      },
    ];
    return { players, teams };
  }

  // Overrides the genId method to ensure that a player always has an id.
  // If the heroes array is empty,
  // the method below returns the initial number (1).
  // if the heroes array is not empty, the method below returns the highest
  // player id + 1.

  genId(players: Player[]): number {
    return players.length > 0
      ? Math.max(...players.map((player) => player.id)) + 1
      : 1;
  }
}
